SUPABASE_URL="https://eqgwnokhvctdddgqqqsv.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZ3dub2todmN0ZGRkZ3FxcXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NTY3MzUsImV4cCI6MjA3NzMzMjczNX0.kifE7BqCCZgssA6N6D1TUgz39A918poXCgdDwJcRyIA"
